### PR TITLE
Functional tests

### PR DESCRIPTION
**Pull request by analogue**
The majority of the legacy functional tests that used HTTPretty have been converted over to pytest and Swagger 2.0. They now live in `tests/functional`.  Also, I added support for `collectionFormat` in requests when `type: array`.

Probabably needs a few more updates but I'm all pytest'ed out for the time being.

### CODE REVIEW

**Comment by analogue** [comment]
Tests are passing fine locally. Dunno whats up with travis.

**Comment by dnephin** [comment]
I'll try running them locally

**Comment by dnephin** [comment]
lgtm once we figure out the travis failures

**Comment by dnephin** [comment]
I only get one flake8 failure when I run this branch locally

**Pull request merged**
