### PR TITLE
Force headers implementation - override header values if passed through request

### LINKED ISSUE #31: Add support for 'header' request parameter

### PR DESCRIPTION
**Pull request by prat0318**
Fixes #31.

### CODE REVIEW

**Comment by dnephin** [comment]
We have a feature that requires header support. @prat0318 let me know if you're able to work on this or not.  They need something by next wednesday, so I can take this over if you're occupied with other things.

**Comment by prat0318** [comment]
yeah, i can pick it up next.

**Comment by prat0318** [comment]
So, on reading again, this PR looks no longer useful. This PR read `header` param from the request (and obey the spec) as well as another optional attribute `headers_forced` which will override any of the attributes provided in the request's `header` param (don't remember the use-case of it though). Separately specifying the header attributes has now been covered in @e4b888f . I will create a separate PR fetching the `header` param as per spec from the request.

**Comment by prat0318** [comment]
Closing it. Follow up in #122

**Pull request closed without merging**
